version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  nodejs:
    docker:
      - image: circleci/node:latest

jobs:
  create_version:
    executor: nodejs
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7a:87:36:8b:75:2c:67:c0:03:ef:5e:93:00:04:9f:6b"
      - run:
          name: Setup GIT email
          command: git config --global user.email "developer@keen.io"
      - run:
          name: Setup GIT user
          command: git config --global user.name "Keen Developer"
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Create release version
          command: |
            if [ "$CIRCLE_BRANCH" = "develop" ]; then
              yarn release --prerelease rc --skip.changelog
            elif [ "$CIRCLE_BRANCH" = "master" ]; then
              yarn release
            fi
      - run:
          name: Push changes
          command: git push --follow-tags --set-upstream origin ${CIRCLE_BRANCH}
  publish:
    executor: nodejs
    working_directory: ~/tmp
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp/dist
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish
          command: yarn publish
  publish-prerelease:
    executor: nodejs
    working_directory: ~/tmp
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp/dist
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish
          command: yarn publish --tag next
  build:
    executor: nodejs
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: npm-deps-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Unit Tests
          command: yarn test:ci
      - run:
          name: Upload code coverage
          command: |
            if [ "$CIRCLE_BRANCH" = "develop" ]; then
              npx codecov --token=$CODECOV_TOKEN
            fi
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: dist
          paths:
            - "*"

workflows:
  version: 2
  create_version:
    jobs:
      - create_version:
          filters:
            branches:
              only:
                - develop
                - master
            tags:
              ignore: /.*/
  ci:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
  publish-prerelease:
    jobs:
      - build:
          filters:
            tags:
              only: /^.*rc.*$/
            branches:
              ignore: /.*/
      - publish-prerelease:
          filters:
            tags:
              only: /^.*rc.*$/
            branches:
              ignore: /.*/
          requires:
            - build
  publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - publish:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
          requires:
            - build
