version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  nodejs:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    executor: nodejs
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: npm-deps-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Unit Tests
          command: yarn test:ci
      - run:
          name: Build
          command: yarn build
      - slack/status:
          fail_only: false
workflows:
  version: 2
  ci:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
