export const FETCH_DASHBOARDS_LIST = '@dashboards/FETCH_DASHBOARDS_LIST';
export const FETCH_DASHBOARDS_LIST_SUCCESS =
  '@dashboards/FETCH_DASHBOARDS_LIST_SUCCESS';
export const FETCH_DASHBOARDS_LIST_ERROR =
  '@dashboards/FETCH_DASHBOARDS_LIST_ERROR';
export const SET_DASHBOARD_LIST = '@dashboards/SET_DASHBOARD_LIST';
export const CREATE_DASHBOARD = '@dashboards/CREATE_DASHBOARD';
export const SHARE_DASHBOARD = '@dashboards/SHARE_DASHBOARD';
export const DELETE_DASHBOARD = '@dashboards/DELETE_DASHBOARD';
export const DELETE_DASHBOARD_SUCCESS = '@dashboards/DELETE_DASHBOARD_SUCCESS';
export const CLONE_DASHBOARD = '@dashboards/CLONE_DASHBOARD';
export const EDIT_DASHBOARD = '@dashboards/EDIT_DASHBOARD';
export const VIEW_DASHBOARD = '@dashboards/VIEW_DASHBOARD';
export const VIEW_PUBLIC_DASHBOARD = '@dashboards/VIEW_PUBLIC_DASHBOARD';
export const REGISTER_DASHBOARD = '@dashboards/REGISTER_DASHBOARD';
export const DEREGISTER_DASHBOARD = '@dashboards/DEREGISTER_DASHBOARD';
export const UPDATE_DASHBOARD = '@dashboards/UPDATE_DASHBOARD';
export const SET_DASHBOARD_ERROR = '@dashboards/SET_DASHBOARD_ERROR';
export const SAVE_DASHBOARD_METADATA = '@dashboards/SAVE_DASHBOARD_METADATA';
export const SAVE_DASHBOARD_METADATA_SUCCESS =
  '@dashboards/SAVE_DASHBOARD_METADATA_SUCCESS';
export const SAVE_DASHBOARD_METADATA_ERROR =
  '@dashboards/SAVE_DASHBOARD_METADATA_ERROR';
export const UPDATE_DASHBOARD_METADATA =
  '@dashboards/UPDATE_DASHBOARD_METADATA';
export const SAVE_DASHBOARD = '@dashboards/SAVE_DASHBOARD';
export const SAVE_DASHBOARD_SUCCESS = '@dashboards/SAVE_DASHBOARD_SUCCESS';
export const SAVE_DASHBOARD_ERROR = '@dashboards/SAVE_DASHBOARD_ERROR';
export const ADD_WIDGET_TO_DASHBOARD = '@dashboards/ADD_WIDGET_TO_DASHBOARD';
export const REMOVE_WIDGET_FROM_DASHBOARD =
  '@dashboards/REMOVE_WIDGET_FROM_DASHBOARD';
export const INITIALIZE_DASHBOARD_WIDGETS =
  '@dashboards/INITIALIZE_DASHBOARD_WIDGETS';
export const SHOW_DELETE_CONFIRMATION = '@dashboards/SHOW_DELETE_CONFIRMATION';
export const HIDE_DELETE_CONFIRMATION = '@dashboards/HIDE_DELETE_CONFIRMATION';
export const CONFIRM_DASHBOARD_DELETE = '@dashboards/CONFIRM_DASHBOARD_DELETE';
export const SHOW_DASHBOARD_SETTINGS_MODAL =
  '@dashboards/SHOW_DASHBOARD_SETTINGS_MODAL';
export const HIDE_DASHBOARD_SETTINGS_MODAL =
  '@dashboards/HIDE_DASHBOARD_SETTINGS_MODAL';
export const SHOW_DASHBOARD_SHARE_MODAL =
  '@dashboards/SHOW_DASHBOARD_SHARE_MODAL';
export const HIDE_DASHBOARD_SHARE_MODAL =
  '@dashboards/HIDE_DASHBOARD_SHARE_MODAL';
export const SET_DASHBOARD_LIST_ORDER = '@dashboards/SET_DASHBOARD_LIST_ORDER';
export const SET_DASHBOARD_PUBLIC_ACCESS =
  '@dashboards/SET_DASHBOARD_PUBLIC_ACCESS';
export const UPDATE_ACCESS_KEY_OPTIONS =
  '@dashboards/UPDATE_ACCESS_KEY_OPTIONS';
export const REGENERATE_ACCESS_KEY = '@dashboards/REGENERATE_ACCESS_KEY';
export const REGENERATE_ACCESS_KEY_SUCCESS =
  '@dashboards/REGENERATE_ACCESS_KEY_SUCCESS';
export const REGENERATE_ACCESS_KEY_ERROR =
  '@dashboards/REGENERATE_ACCESS_KEY_ERROR';
export const ADD_CLONED_DASHBOARD = '@dashboard/ADD_CLONED_DASHBOARD';
export const EXPORT_DASHBOARD_TO_HTML = '@dashboard/EXPORT_DASHBOARD_TO_HTML';
export const PREPARE_TAGS_POOL = '@dashboard/PREPARE_TAGS_POOL';
export const CLEAR_TAGS_POOL = '@dashboard/CLEAR_TAGS_POOL';
export const SET_TAGS_FILTERS = '@dashboard/SET_TAGS_FILTERS';
export const SET_TAGS_FILTERS_PUBLIC = '@dashboard/SET_TAGS_FILTERS_PUBLIC';
export const UPDATE_CACHED_DASHBOARD_IDS =
  '@dashboard/UPDATE_CACHED_DASHBOARD_IDS';
export const UNREGISTER_DASHBOARD = '@dashboard/UNREGISTER_DASHBOARD';
export const CALCULATE_Y_POSITION_AND_ADD_WIDGET =
  '@dashboard/CALCULATE_Y_POSITION_AND_ADD_WIDGET';

export const DASHBOARD_LIST_ORDER_KEY =
  '@keen-dashboard-creator/dashboard-list-order';

export const PUBLIC_DASHBOARD_ID = '@keen-dashboard-creator';

export const DASHBOARDS_ORDER = {
  recent: 'Recent',
  oldest: 'Oldest',
  az: 'A - Z',
  za: 'Z - A',
};
