export const OPEN_EDITOR = '@filter/OPEN_EDITOR';
export const CLOSE_EDITOR = '@filter/CLOSE_EDITOR';
export const RESET_EDITOR = '@filter/RESET_EDITOR';
export const APPLY_EDITOR_SETTINGS = '@filter/APPLY_SETTINGS';
export const SET_EDITOR_CONNECTIONS = '@filter/SET_EDITOR_CONNECTIONS';
export const UPDATE_CONNECTION = '@filter/UPDATE_CONNECTION';
export const SET_TARGET_PROPERTY = '@filter/SET_TARGET_PROPERTY';
export const SET_EVENT_STREAM = '@filter/SET_EVENT_STREAM';
export const SETUP_DASHBOARD_EVENT_STREAMS =
  '@filter/SETUP_DASHBOARD_EVENT_STREAMS';
export const SET_EVENT_STREAMS_POOL = '@filter/SET_EVENT_STREAMS_POOL';
export const SET_EVENT_STREAM_SCHEMA = '@filter/SET_EVENT_STREAM_SCHEMA';
export const SET_SCHEMA_PROCESSING = '@filter/SET_SCHEMA_PROCESSING';
export const SET_SCHEMA_PROCESSING_ERROR =
  '@filter/SET_SCHEMA_PROCESSING_ERROR';

export const FILTER_SCHEMA_PROPERTY_TYPE = 'string';
