export const REGISTER_WIDGETS = '@widgets/REGISTER_WIDGETS';
export const UPDATE_WIDGETS_POSITION = '@widgets/UPDATE_WIDGETS_POSITION';
export const CREATE_WIDGET = '@widgets/CREATE_WIDGET';
export const REMOVE_WIDGET = '@widgets/REMOVE_WIDGET';
export const START_VISUALIZATION_WIZARD = '@widgets/START_VISUALIZATION_WIZARD';
export const SET_WIDGET_STATE = '@widgets/SET_WIDGET_STATE';
export const SET_WIDGET_LOADING = '@widgets/SET_WIDGET_LOADING';
export const SET_WIDGET_INITIALIZATION = '@widgets/SET_WIDGET_INITIALIZATION';
export const INITIALIZE_WIDGET = '@widgets/INITIALIZE_WIDGET';
export const INITIALIZE_CHART_WIDGET = '@widgets/INITIALIZE_CHART_WIDGET';
export const FINISH_CHART_WIDGET_CONFIGURATION =
  '@widgets/FINISH_CHART_WIDGET_CONFIGURATION';
