export const REGISTER_WIDGETS = '@widgets/REGISTER_WIDGETS';
export const UPDATE_WIDGETS_POSITION = '@widgets/UPDATE_WIDGETS_POSITION';
export const CREATE_WIDGET = '@widgets/CREATE_WIDGET';
export const REMOVE_WIDGET = '@widgets/REMOVE_WIDGET';
export const START_VISUALIZATION_WIZARD = '@widgets/START_VISUALIZATION_WIZARD';

export const OPEN_CHART_WIDGET_EDITOR = '@widgets/OPEN_CHART_WIDGET_EDITOR';
export const CLOSE_CHART_WIDGET_EDITOR = '@widgets/CLOSE_CHART_WIDGET_EDITOR';
export const RESET_CHART_WIDGET_EDITOR = '@widgets/RESET_CHART_WIDGET_EDITOR';
export const CHART_WIDGET_EDITOR_RUN_QUERY =
  '@widgets/CHART_WIDGET_EDITOR_RUN_QUERY';
export const CHART_WIDGET_EDITOR_RUN_QUERY_SUCCESS =
  '@widgets/CHART_WIDGET_EDITOR_RUN_QUERY_SUCCESS';
export const CHART_WIDGET_EDITOR_RUN_QUERY_ERROR =
  '@widgets/CHART_WIDGET_EDITOR_RUN_QUERY_ERROR';
export const CHART_WIDGET_EDITOR_SET_QUERY_SETTINGS =
  '@widgets/CHART_WIDGET_EDITOR_SET_QUERY_SETTINGS';
export const CHART_WIDGET_EDITOR_MOUNTED =
  '@widgets/CHART_WIDGET_EDITOR_MOUNTED';
export const CHART_WIDGET_EDITOR_APPLY_CONFIGURATION =
  '@widgets/CHART_WIDGET_EDITOR_APPLY_CONFIGURATION';

export const SET_WIDGET_STATE = '@widgets/SET_WIDGET_STATE';
export const SET_WIDGET_LOADING = '@widgets/SET_WIDGET_LOADING';
export const SET_WIDGET_INITIALIZATION = '@widgets/SET_WIDGET_INITIALIZATION';
export const INITIALIZE_WIDGET = '@widgets/INITIALIZE_WIDGET';
export const INITIALIZE_CHART_WIDGET = '@widgets/INITIALIZE_CHART_WIDGET';
export const FINISH_CHART_WIDGET_CONFIGURATION =
  '@widgets/FINISH_CHART_WIDGET_CONFIGURATION';
