export const REGISTER_WIDGETS = '@widgets/REGISTER_WIDGETS';
export const UPDATE_WIDGETS_POSITION = '@widgets/UPDATE_WIDGETS_POSITION';
export const CREATE_WIDGET = '@widgets/CREATE_WIDGET';
export const REMOVE_WIDGET = '@widgets/REMOVE_WIDGET';
export const START_VISUALIZATION_WIZARD = '@widgets/START_VISUALIZATION_WIZARD';
export const SET_WIDGET_STATE = '@widgets/SET_WIDGET_STATE';
export const SET_WIDGET_LOADING = '@widgets/SET_WIDGET_LOADING';
export const SET_WIDGET_INITIALIZATION = '@widgets/SET_WIDGET_INITIALIZATION';
export const INITIALIZE_WIDGET = '@widgets/INITIALIZE_WIDGET';
export const INITIALIZE_CHART_WIDGET = '@widgets/INITIALIZE_CHART_WIDGET';
export const UPDATE_CHART_WIDGET_DATE_PICKER_CONNECTION =
  '@widgets/UPDATE_CHART_WIDGET_DATE_PICKER_CONNECTION';
export const EDIT_CHART_WIDGET = '@widgets/EDIT_CHART_WIDGET';
export const EDIT_IMAGE_WIDGET = '@widgets/EDIT_IMAGE_WIDGET';
export const EDIT_TEXT_WIDGET = '@widgets/EDIT_TEXT_WIDGET';
export const EDIT_INLINE_TEXT_WIDGET = '@widgets/EDIT_INLINE_TEXT_WIDGET';
export const SET_IMAGE_WIDGET = '@widgets/SET_IMAGE_WIDGET';
export const SET_TEXT_WIDGET = '@widgets/SET_TEXT_WIDGET';
export const FINISH_CHART_WIDGET_CONFIGURATION =
  '@widgets/FINISH_CHART_WIDGET_CONFIGURATION';
export const SAVED_QUERY_UPDATED = '@widgets/SAVED_QUERY_UPDATED';
export const SAVE_CLONED_WIDGET = '@widgets/SAVE_CLONED_WIDGET';
export const CLONE_WIDGET = '@widgets/CLONE_WIDGET';
export const SAVE_IMAGE = '@widgets/SAVE_IMAGE';
export const SET_DATE_PICKER_WIDGET = '@widgets/SET_DATE_PICKER_WIDGET';
export const EDIT_DATE_PICKER_WIDGET = '@widgets/EDIT_DATE_PICKER_WIDGET';
export const RESET_DATE_PICKER_WIDGETS = '@widgets/RESET_DATE_PICKER_WIDGETS';
export const SET_DATE_PICKER_WIDGET_MODIFIERS =
  '@widgets/SET_DATE_PICKER_WIDGET_MODIFIERS';
export const CLEAR_DATE_PICKER_MODIFIERS =
  '@widgets/CLEAR_DATE_PICKER_MODIFIERS';
export const APPLY_DATE_PICKER_MODIFIERS =
  '@widgets/APPLY_DATE_PICKER_MODIFIERS';
export const CONFIGURE_FILTER_WIDGET = '@widgets/CONFIGURE_FILTER_WIDGET';
export const EDIT_FILTER_WIDGET = '@widgets/EDIT_FILTER_WIDGET';
export const UPDATE_CHART_WIDGET_FILTERS_CONNECTIONS =
  '@widgets/UPDATE_CHART_WIDGET_FILTERS_CONNECTIONS';
export const SET_FILTER_WIDGET = '@widgets/SET_FILTER_WIDGET';
export const SET_FILTER_PROPERTY_LIST = '@widgets/SET_FILTER_PROPERTY_LIST';
export const APPLY_FILTER_WIDGET = '@widgets/APPLY_FILTER_WIDGET';
export const UNAPPLY_FILTER_WIDGET = '@widgets/UNAPPLY_FILTER_WIDGET';
