export const SET_BASE_THEME = '@theme/SET_BASE_THEME';
export const UPDATE_BASE_THEME = '@theme/UPDATE_BASE_THEME';
export const RESET_BASE_THEME = '@theme/RESET_BASE_THEME';
export const UPDATE_DASHBOARD_THEME = '@theme/UPDATE_DASHBOARD_THEME';
export const REMOVE_DASHBOARD_THEME = '@theme/REMOVE_DASHBOARD_THEME';
